# Test your FastAPI endpoints
GET http://127.0.0.1:8000/stream
Accept: application/json

###

GET 127.0.0.1:8000/stream/octocat/Hello-World
Accept: application/json

###

GET 127.0.0.1:8000/pr-time/octocat/Hello-World
Accept: application/json

###

GET 127.0.0.1:8000/events/10
Accept: application/json